dcgm-exporter:
  runtimeClassName: nvidia

  nodeSelector:
    accelerator: nvidia
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  serviceMonitor:
    enabled: true
