apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.io/category: ci
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default

  source:
    repoURL: https://github.com/rubenspensky-homelab/homelab-infra.git
    targetRevision: main
    path: infrastructure/arc-runner-set

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
