apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-crds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.io/category: security
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default

  source:
    repoURL: https://github.com/rubenspensky-homelab/homelab-infra.git
    targetRevision: main
    path: infrastructure/external-secrets-crds

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
