apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.io/category: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: default

  source:
    repoURL: https://github.com/rubenspensky-homelab/homelab-infra.git
    targetRevision: main
    path: infrastructure/metallb-config

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
