apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default

  source:
    repoURL: https://github.com/rubenspensky-homelab/homelab-infra.git
    targetRevision: main
    path: infrastructure/umami

  destination:
    server: https://kubernetes.default.svc
    namespace: analytics

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
