kube-prometheus-stack:
  fullnameOverride: prometheus-stack

  grafana:
    enabled: true
    adminPassword: admin

    service:
      type: ClusterIP

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folderAnnotation: grafana_folder
        searchNamespace: monitoring

    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        isDefault: false
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.logging.svc.cluster.local:3200
        isDefault: false

  prometheus:
    prometheusSpec:
      retention: 7d

      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 2Gi

      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: true

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true
