apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app
  namespace: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: arc-github-app
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: github_app_id
      remoteRef:
        key: homelab/github/arc-app
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: homelab/github/arc-app
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: homelab/github/arc-app
        property: github_app_private_key
