apiVersion: v2
name: metrics-server-wrapper
description: Wrapper chart for metrics-server in the homelab cluster
type: application
version: 0.1.0

dependencies:
  - name: metrics-server
    version: 3.13.1
    repository: https://kubernetes-sigs.github.io/metrics-server/
