apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-grafana
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: homelab-postgres
  name: grafana
  owner: grafana
  databaseReclaimPolicy: retain
