apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-database-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GF_DATABASE_USER: grafana
        GF_DATABASE_PASSWORD: "{{ `{{ .databasePassword }}` }}"
  data:
    - secretKey: databasePassword
      remoteRef:
        key: /homelab/grafana
        property: databasePassword
