apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-db-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: umami-db-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: umami
        password: "{{ .databasePassword }}"
  data:
    - secretKey: databasePassword
      remoteRef:
        key: /homelab/umamik
        property: databasePassword
