apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-config
  namespace: analytics
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: umami-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://umami:{{ .databasePassword }}@homelab-postgres-rw.databases.svc.cluster.local:5432/umami"
        APP_SECRET: "{{ .appSecret }}"
  data:
    - secretKey: databasePassword
      remoteRef:
        key: /homelab/umamik
        property: databasePassword
    - secretKey: appSecret
      remoteRef:
        key: /homelab/umamik
        property: appSecret
