apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-brand-blueprints
  namespace: authentik
data:
  homelab-brand.yaml: |
    version: 1

    metadata:
      name: Homelab Brand

    entries:
      - model: authentik_brands.brand
        state: present
        identifiers:
          domain: auth.home.lab
        attrs:
          default: false
          branding_title: Homelab Lab Auth

          branding_custom_css: |
            :root {
              --pf-global--primary-color--100: #0f766e;
              --pf-global--primary-color--200: #115e59;
              --pf-global--link--Color: #14b8a6;
            }

            .pf-c-button.pf-m-primary,
            button[type="submit"] {
              background: linear-gradient(
                135deg,
                #0f766e,
                #14b8a6
              ) !important;
              border: none !important;
            }

            .pf-c-login__main {
              border-radius: 18px;
              box-shadow: 0 20px 60px rgba(15, 118, 110, 0.35);
            }

      - model: authentik_brands.brand
        state: present
        identifiers:
          domain: auth.rubenspensky.com
        attrs:
          default: false
          branding_title: Rubenspensky Auth

          branding_logo: >-
            https://raw.githubusercontent.com/rubenspensky-homelab/homelab-infra/main/infrastructure/authentik/assets/logo.svg

          branding_favicon: >-
            https://raw.githubusercontent.com/rubenspensky-homelab/homelab-infra/main/infrastructure/authentik/assets/favicon.png

          branding_default_flow_background: >-
            https://raw.githubusercontent.com/rubenspensky-homelab/homelab-infra/main/infrastructure/authentik/assets/homelab-backrgound.png

          flow_enrollment: !Find
            - authentik_flows.flow
            - [slug, user-registration]

          branding_custom_css: |
            @import url("https://raw.githubusercontent.com/rubenspensky-homelab/homelab-infra/main/infrastructure/authentik/assets/brand.css");
