apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: authentik-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AUTHENTIK_SECRET_KEY: "{{ `{{ .secretKey }}` }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ `{{ .databasePassword }}` }}"
  data:
    - secretKey: secretKey
      remoteRef:
        key: /homelab/authentik
        property: secretKey
    - secretKey: databasePassword
      remoteRef:
        key: /homelab/authentik
        property: databasePassword
