apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: authentik
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  cluster:
    name: homelab-postgres
  name: authentik
  login: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: authentik-db-auth
