apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CDI v1.65.0 official release assets:
# https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.65.0
resources:
  - cdi-operator.yaml
  - cdi-cr.yaml

patches:
  - target:
      group: cdi.kubevirt.io
      version: v1beta1
      kind: CDI
      name: cdi
    patch: |-
      - op: add
        path: /metadata/namespace
        value: cdi
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
