apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 0
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: tunnel-token-eso
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: homelab/cloudflare/tunnel-token
        property: token
