gha-runner-scale-set:
  githubConfigUrl: https://github.com/rubenspensky-homelab
  githubConfigSecret: arc-github-app

  minRunners: 0
  maxRunners: 3

  controllerServiceAccount:
    namespace: arc-systems
    name: arc-controller-gha-rs-controller

  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:2.335.1@sha256:08c30b0a7105f64bddfc485d2487a22aa03932a791402393352fdf674bda2c29
          command:
            - /home/runner/run.sh
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 3Gi
