# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Homelab - Demo Users
  labels:
    blueprints.goauthentik.io/description: Group for users created through the public demo registration flow.

entries:
  - model: authentik_core.group
    state: present
    id: demo-users-group
    identifiers:
      name: demo-users
    attrs:
      name: demo-users
      is_superuser: false
