apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: buildkit
  labels:
    app.kubernetes.io/name: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkit
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.31.2-rootless@sha256:0eeb84626c0cd01aecae7848c5ed8f095aec279dd936d0cdb5a64110f42ca65b
          imagePullPolicy: IfNotPresent
          args:
            - --addr
            - tcp://0.0.0.0:1234
            - --oci-worker-no-process-sandbox
          ports:
            - name: buildkit
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: buildkit
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: buildkit
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - name: buildkit-cache
              mountPath: /home/user/.local/share/buildkit
      volumes:
        - name: buildkit-cache
          persistentVolumeClaim:
            claimName: buildkit-cache
